project_name: concurrent-swiss-map

release:
  github:
    name: concurrent-swiss-map
    owner: mhmtszr

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^docs:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy